quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=hightech_user
quarkus.datasource.password=hightech_pass123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/hightech_inventario_db

# ─── JWT ─────────────────────────────────────────────────
mp.jwt.verify.issuer=https://hightech.com
quarkus.smallrye-jwt.enabled=true

# ─── OpenAPI ─────────────────────────────────────────────
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# ─── Hibernate ───────────────────────────────────────────
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false