#Servidor

quarkus.http.port=8081

#bases de datos

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=hightech_user
quarkus.datasource.password=hightech_pass123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/hightech_auth_db
