# ─── Servidor ────────────────────────────────────────────
quarkus.http.port=8084

# ─── Base de datos ───────────────────────────────────────
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=hightech_user
quarkus.datasource.password=hightech_pass123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/hightech_geo_db

# ─── JWT ─────────────────────────────────────────────────
mp.jwt.verify.issuer=https://hightech.com
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.publickey.location=keys/publicKey.pem

# ─── OpenAPI ─────────────────────────────────────────────
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# ─── Hibernate ───────────────────────────────────────────
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization